// Generated by CoffeeScript 1.8.0
(function() {
  exports.getLocalTime = function(nS) {
    var day, month, time, year;
    year = new Date(parseInt(nS) * 1000).getFullYear();
    month = new Date(parseInt(nS) * 1000).getMonth() + 1;
    if (month < 10) {
      month = '0' + month;
    }
    day = new Date(parseInt(nS) * 1000).getDate();
    if (day < 10) {
      day = '0' + day;
    }
    time = year + '-' + month + '-' + day;
    return time;
  };

  exports.loadJSON = function(data) {
    var res;
    try {
      return res = JSON.parse(data);
    } catch (_error) {

    }
  };

}).call(this);

//# sourceMappingURL=help.js.map
