// Generated by CoffeeScript 1.8.0
(function() {
  var GenMapImg, MIME_TO_EXTESION_MAPPING, async, fs, getLocalTime, gmi, request;

  request = require('request');

  async = require('async');

  fs = require('fs');

  getLocalTime = require('../help').getLocalTime;

  MIME_TO_EXTESION_MAPPING = {
    'image/png': '.png',
    'image/jpg': '.jpg',
    'image/jpeg': '.jpg',
    'image/gif': '.gif'
  };

  GenMapImg = (function() {
    function GenMapImg(deviceInfo) {
      var baidu, longLat;
      this.deviceInfo = deviceInfo;
      baidu = process.env.baidu;
      longLat = this.deviceInfo.long + ',' + this.deviceInfo.lat;
      this.url = "http://api.map.baidu.com/staticimage?width=800&height=700&zoom=16&dpiType=ph" + "&center=" + longLat + '&markers=' + longLat + '&ak=' + baidu;
    }

    GenMapImg.prototype.getImg = function(cb) {
      var self;
      self = this;
      return async.waterfall([
        function(callback) {
          var op;
          op = {
            url: self.url,
            encoding: 'binary'
          };
          return request.get(op, function(err, res, body) {
            var image, mimeType;
            if (err) {
              return console.log(err);
            }
            mimeType = res.headers['content-type'];
            mimeType = mimeType.split(';')[0];
            image = new Buffer(body, 'binary');
            return callback(null, image, mimeType);
          });
        }, function(image, mimeType, callback) {
          var baseDir, checkTime, dir, fileRes, locationTime;
          baseDir = __dirname + '/static';
          checkTime = getLocalTime(self.deviceInfo.check_time);
          locationTime = getLocalTime(self.deviceInfo.location_time);
          fileRes = baseDir + '/' + checkTime + '/' + locationTime + MIME_TO_EXTESION_MAPPING[mimeType];
          dir = baseDir + '/' + checkTime;
          if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir);
          }
          fs.writeFileSync(fileRes, image);
          return console.log("write ok");
        }
      ]);
    };

    return GenMapImg;

  })();

  gmi = new GenMapImg({
    long: 114.0296431124400,
    lat: 22.6402391251580,
    check_time: 1438094699,
    location_time: 1438094631
  });

  console.log(__dirname);

  console.log(process.cwd());

  gmi.getImg();

}).call(this);

//# sourceMappingURL=gen_map_img.js.map
