// Generated by CoffeeScript 1.8.0
(function() {
  var T, toshihiko;

  T = require("toshihiko");

  toshihiko = new T.Toshihiko('find_my', 'root', '', {});

  module.exports = toshihiko;

}).call(this);

//# sourceMappingURL=toshihiko.js.map
